export { PGliteEngine } from './core/storage/pglite.js'
export type { PGliteEngineOptions } from './core/storage/pglite.js'
export { OpenAIEmbedding } from './core/embedding/openai.js'
export { TokenCounter } from './core/token/counter.js'
export { TokenBudgetEnforcer, DEFAULT_TOKEN_BUDGET } from './core/token/budget.js'
export { HybridSearch } from './core/search/hybrid.js'
export { classifyIntent } from './core/search/intent.js'
export type { QueryIntent, IntentResult } from './core/search/intent.js'
export { vectorSearch } from './core/search/vector.js'
export { keywordSearch } from './core/search/keyword.js'
export { PGliteSemanticCache, DEFAULT_CACHE_THRESHOLD, DEFAULT_CACHE_TTL_SECONDS } from './core/cache/pglite-cache.js'
export { NoOpExpander } from './core/expand/noop.js'
export { LLMExpander } from './core/expand/llm.js'
export type { ExpandFn } from './core/expand/llm.js'
export { PGliteKnowledgeGraph } from './core/graph/pglite-graph.js'
export { BacklinkBooster, DEFAULT_BACKLINK_BOOST_FACTOR } from './core/graph/boost.js'
export { extractEntities } from './core/graph/extractor.js'

export type { BrainEngine } from './core/engine.js'
export type { BrainPage, BrainPageInput, SearchResult, SearchOptions } from './core/types.js'
export type { EmbeddingProvider } from './core/embedding/interface.js'
export type { SemanticCache, CacheEntry } from './core/cache/interface.js'
export type { QueryExpander } from './core/expand/interface.js'
export type { KnowledgeGraph, Entity, Relationship, EntityType, RelationshipType } from './core/graph/interface.js'
export type { ExtractedEntity } from './core/graph/extractor.js'

export { createBrainMCPServer } from './mcp/server.js'
